application: rankingpal-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false


default_expiration: "5d"

builtins:
- remote_api: on
    
handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  mime_type: image/x-icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /static
  static_dir: static

- url: /admin.*
  script: main.py
  login: admin  

- url: /.*
  script: main.py